#!/usr/bin/env ruby

require_relative 'lib/lurch'

class REPL
  def run
    loop do
      line = gets.chomp

      exit if line == "exit"

      event = Lurch::Event.new :command, 'sam', line

      Lurch::Handler.match event 
    end
  end

  def accept message
    puts message
  end
end

client = REPL.new
client.run
